name: diagram_editor
description: A Flutter library for building interactive diagram editors with type-safe components, links, pan/zoom, and serialization.
version: 1.0.0
homepage: https://arokip.github.io/fdl_demo_app
repository: https://github.com/Arokip/flutter_diagram_editor

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
